### ISSUE TITLE
No animation on Nexus Player runing AOSP 5.1.1

### ISSUE THREAD

**Issue by thevoiceless** [tajchert/WaitingDots#4] opened 2015-05-15 15:27 UTC
I'm using version 0.2.0 of your library and the dots do not animate. isHide() returns false and isPlaying() returns true. The code I'm using is at https://github.com/thevoiceless/TvBluetoothSetup/tree/waitingDots

It may be worth noting that I am running AOSP compiled for the device, not the stock software from Google (although they should be the same aside from proprietary Google stuff).

Let me know if you need more information.

**Comment by tajchert** [comment] 2015-05-15 18:05
Hi, thanks for reporting an issue. Please also try using 0.1.0 version as it wasn't based on `Animation` objects - maybe this is a problem.
I will try to reproduce problem on some phone.

**Comment by thevoiceless** [comment] 2015-05-16 00:02
Sure! I'll let you know on Monday if 0.1.0 makes a difference. 

If you're unable to reproduce the issue on a phone, I do know that the emulator supports Android TV (including HAXM).

**Comment by thevoiceless** [comment] 2015-05-18 16:07
Hello!
I just tested 0.1.0 and the animation works (I had to comment out a call to setText() in my code since it doesn't extend TextView, but that was the only issue).

**Comment by alexvasilkov** [comment] 2015-11-10 13:58
Hi, I also encountered this issue and it looks like a bug of TextView, which will not draw ReplacementSpan if all characters in text are using this span. I haven't found exact problem, but I found a simple workaround:

```
dotsView.setText(new SpannableStringBuilder(dots.getText()).append("\u200b"));
```

Where `\u200b` is zero-width character.

**Comment by tajchert** [comment] 2016-04-21 14:30
This is fixed with pull request https://github.com/tajchert/WaitingDots/pull/9
Thanks all you!

**Closed as completed by tajchert** 2016-04-21 14:30 UTC
